// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_WoyLUbm0SeFj0eEbO4tIMyHNmPSCIVc',
    appId: '1:708583674473:web:da84a0e215324681d808f8',
    messagingSenderId: '708583674473',
    projectId: 'livestockmanager-74f7d',
    authDomain: 'livestockmanager-74f7d.firebaseapp.com',
    storageBucket: 'livestockmanager-74f7d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtq1h5bgBs3ouwyLzhHO6H8SY07qCKMBs',
    appId: '1:708583674473:android:4fe01b3e1071f380d808f8',
    messagingSenderId: '708583674473',
    projectId: 'livestockmanager-74f7d',
    storageBucket: 'livestockmanager-74f7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw0aBgIrwPXJ2eVk_MOhmkfNN5ywrvs_s',
    appId: '1:708583674473:ios:950bdd3baf4a73fed808f8',
    messagingSenderId: '708583674473',
    projectId: 'livestockmanager-74f7d',
    storageBucket: 'livestockmanager-74f7d.firebasestorage.app',
    iosBundleId: 'com.example.flutterMaturaprojektV01',
  );

}